const blocked=["epstein"];const defaults={theme:"dark",accent:"#7c5cff",perPage:36,compact:false};let prefs={...defaults,...JSON.parse(localStorage.getItem("hi-games-prefs")||"{}")};
const themes={dark:["#0b0c10","#15171e","#1d2029","#f5f7fb","#a7adbb","#2a2e3a"],light:["#f5f6fa","#ffffff","#edf0f5","#171923","#667085","#dfe3ea"],violet:["#160d22","#211330","#2d1a40","#faf5ff","#c6b4d6","#44265d"],blue:["#071820","#0d2631","#123441","#effcff","#a9c8d0","#1f5260"],green:["#0b1911","#11251a","#173323","#f1fff5","#afc7b6","#28543a"],red:["#21100f","#321716","#43201d","#fff5f3","#dcbab5","#66342f"],amber:["#211807","#30240d","#433415","#fff9ed","#dac99f","#665226"],pink:["#211018","#321721","#43202d","#fff5f8","#dcb9c6","#663342"],gray:["#171717","#202020","#292929","#f4f4f4","#b5b5b5","#3b3b3b"],midnight:["#070b1a","#0d1430","#121d40","#f1f5ff","#aebce0","#263665"]};
function apply(){let t=themes[prefs.theme]||themes.dark;let r=document.documentElement;r.style.setProperty("--bg",t[0]);r.style.setProperty("--surface",t[1]);r.style.setProperty("--surface2",t[2]);r.style.setProperty("--text",t[3]);r.style.setProperty("--muted",t[4]);r.style.setProperty("--line",t[5]);r.style.setProperty("--accent",prefs.accent);document.body.classList.toggle("compact",prefs.compact);localStorage.setItem("hi-games-prefs",JSON.stringify(prefs))}
apply();

document.querySelectorAll("[data-theme]").forEach(b=>{b.classList.toggle("selected",b.dataset.theme===prefs.theme);b.onclick=()=>{prefs.theme=b.dataset.theme;apply();document.querySelectorAll("[data-theme]").forEach(x=>x.classList.toggle("selected",x===b))}});
document.querySelectorAll("[data-accent]").forEach(b=>b.onclick=()=>{prefs.accent=b.dataset.accent;apply()});
let pp=document.getElementById("per-page");if(pp){pp.value=prefs.perPage;pp.onchange=()=>{prefs.perPage=+pp.value;apply()}}let cp=document.getElementById("compact");if(cp){cp.checked=prefs.compact;cp.onchange=()=>{prefs.compact=cp.checked;apply()}}let reset=document.getElementById("reset");if(reset)reset.onclick=()=>{localStorage.removeItem("hi-games-prefs");location.reload()};

const grid=document.getElementById("games");if(grid){let page=1,pages=1,query="",timer;
const status=document.getElementById("status"),count=document.getElementById("game-count"),info=document.getElementById("page-info"),pagination=document.getElementById("pagination");
const allowed=g=>!blocked.some(w=>String(g.name||"").toLowerCase().includes(w));
async function load(){status.style.display="block";status.textContent="Loading games...";grid.innerHTML="";try{let res=await Lumin.getGames({page,limit:prefs.perPage,q:query});pages=Number(res.pages||1);let games=(res.games||[]).filter(allowed);let imgs=await Promise.all(games.map(async g=>{try{return await Lumin.getImageUrl(g.image_token)}catch{return""}}));games.forEach((g,i)=>{let card=document.createElement("article");card.className="game";if(imgs[i]){let im=document.createElement("img");im.src=imgs[i];im.alt=g.name||"Game";im.loading="lazy";card.append(im)}let d=document.createElement("div");d.className="info";let n=document.createElement("div");n.className="name";n.textContent=g.name||"Untitled Game";n.title=n.textContent;let play=document.createElement("button");play.className="play";play.textContent="Play";play.onclick=async()=>{try{play.disabled=true;play.textContent="Loading...";await Lumin.loadGame(g.id)}catch(e){console.error(e);alert("This game could not be loaded.")}finally{play.disabled=false;play.textContent="Play"}};d.append(n,play);card.append(d);grid.append(card)});status.style.display=games.length?"none":"block";if(!games.length)status.textContent="No games found.";count.textContent=`${Number(res.total||0).toLocaleString()} games`;info.textContent=`Page ${page} of ${pages}`;renderPages()}catch(e){console.error(e);status.textContent="Failed to load games."}}
function go(n){page=Math.max(1,Math.min(pages,n));load();scrollTo({top:0,behavior:"smooth"})}
function renderPages(){pagination.innerHTML="";let add=(txt,n,disabled=false,current=false)=>{let b=document.createElement("button");b.className="pagebtn"+(current?" current":"")+(n==="prev"||n==="next"?" secondary":"");b.textContent=txt;b.disabled=disabled;b.onclick=()=>go(n==="prev"?page-1:n==="next"?page+1:n);pagination.append(b)};add("←", "prev",page===1);let shown=[];for(let i=1;i<=pages;i++)if(i===1||i===pages||Math.abs(i-page)<=2)shown.push(i);let last=0;shown.forEach(n=>{if(n-last>1){let s=document.createElement("span");s.textContent="…";s.style.padding="10px 4px";pagination.append(s)}add(String(n),n,false,n===page);last=n});add("→","next",page===pages)}
document.getElementById("search").oninput=e=>{clearTimeout(timer);timer=setTimeout(()=>{query=e.target.value.trim();page=1;load()},350)};
(async()=>{try{await Lumin.init({headless:true});load()}catch(e){console.error(e);status.textContent="Could not start the game library."}})();}
